 <div class="container">
        <div class="row">
            <div class="section">
                <div class="col right">
                    <a class='dropdown-button btn' href='#' data-activates='ordenar'>Ordenar</a>

                    <ul id='ordenar' class='dropdown-content'>
                        <?php foreach (getColumnas() as $columna) { ?>
                            <li>
                                <?php if ($columna['ordenUrl']!=null) { ?>
                                    <a href=<?php echo $columna['ordenUrl']; ?>>
                                        <?php echo $columna['name']; ?>
                                    </a>
                                <?php } ?>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col s12">
                <ul class="collection">
                    <?php foreach (getListas() as $list) { ?>
                        <li class="collection-item avatar" id="<?php echo $list['id']; ?>">
                                <?php if ($list['deleteUrl']!=null) { ?>
                                    <a onclick="borrarContacto('<?php echo $list['deleteUrl']; ?>')" class='click'>
                                        <i class="mdi-action-delete"></i>
                                    </a>
                                <?php } ?>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>

    </div>

    
    <!-- Modal Trigger -->
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large waves-effect waves-light red btn modal-trigger" href="#modal"><i class="mdi-content-add"></i></a>
    </div>

        <!-- Modal Structure -->
        <div id="modal" class="modal">
            <form action='./agregarList.php' method='post' class="col s8 offset-s2">
                <div class="modal-content">
                    <div class="row">
                        <div class="input-field col s6">
                          <input id="nombre" name="nombre" type="text" value="Nombre" class="validate">
                          <label for="nombre">Nombre de la Lista</label>
                        </div>
                    </div>  
                </div>
                <div class="modal-footer">
                    <button class="btn waves-effect waves-light modal-action modal-close" type="submit" name="action">Guardar
                        <i class="mdi-content-send right"></i>
                    </button>
                </div>
            </form>
        </div>


