<div class="container">
  <div class="row">
    <div class="section">
      <div class="col s8 offset-s2">
        <div class="card blue-grey darken-1 center">
          <div class="card-content white-text">
            <span class="card-title">Error al subir la Foto</span>
            <p><?php echo $error;?></p>
          </div>
          <div class="card-action">
            <a href="./">Volver</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
