<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Movies</title>

        <link href="css/estilo.css" type="text/css" rel="stylesheet">
        <link href="css/materialize.min.css" type="text/css" rel="stylesheet">
        <link rel="shortcut icon" href="" />

        <script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>        
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <script type="text/javascript" src="js/app.js"></script>
    </head>

    <body>
        <nav>
            <div class="nav-wrapper">
              <a href="./" class="brand-logo center">Movies</a>
              <ul id="nav-mobile" class="right">
                <li><?php printUserData(); ?></li>
              </ul>
            </div>
        </nav>
